import type { Metadata } from "next";

import "../globals.css";
import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared";

export const metadata: Metadata = {
  title: "Жопа писька",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Navbar />
      {children}
      {modal}
      <Footer />
    </main>
  );
}
